### ISSUE TITLE
beta3 bug in calculating read diagnostics

### ISSUE THREAD

**Issue by macmanes** [Blahah/transrate#132] opened 2015-02-24 01:28 UTC
This error crops up as SNAP ends but before SALMON begins.

    transrate -t 10 -a new.trinity.20M.ec.P2.Trinity.fasta -r ../Mus_musculus.GRCm38.pep.all.fa \
    -l /mouse/feeding/SRR797058.P2_1P.fq -i /mouse/feeding/SRR797058.P2_2P.fq

error:

    [ INFO] 2015-02-23 19:33:13 : Calculating read diagnostics...
    /share/transrate-1.0.0.beta3-linux-x86_64/lib/app/lib/transrate/read_metrics.rb:63:in `rename': No such file or directory @ sys_fail2 - (postSample.bam, SRR797058.P2_1P.fq.SRR797058.P2_2P.fq.new.trinity.20M.ec.P2.Trinity.assigned.bam) (Errno::ENOENT)
        from /share/transrate-1.0.0.beta3-linux-x86_64/lib/app/lib/transrate/read_metrics.rb:63:in `run'
        from /share/transrate-1.0.0.beta3-linux-x86_64/lib/app/lib/transrate/transrater.rb:86:in `read_metrics'
        from /share/transrate-1.0.0.beta3-linux-x86_64/lib/app/bin/transrate:276:in `block in <main>'
        from /share/transrate-1.0.0.beta3-linux-x86_64/lib/app/bin/transrate:248:in `each'
        from /share/transrate-1.0.0.beta3-linux-x86_64/lib/app/bin/transrate:248:in `<main>'

`SRR797058.P2_1P.fq.SRR797058.P2_2P.fq.new.trinity.20M.ec.P2.Trinity.bam` and `SRR797058.P2_1P.fq-SRR797058.P2_2P.fq-read_count.txt` created but nothing else.

**Comment by Blahah** [comment] 2015-04-02 17:18
I've not been able to recreate this. I think we'll have to leave this open and revisit if we can get a reproducible example.

**Comment by nestorwendt** [comment] 2015-04-13 01:53
I had the same error. But when I ran transrate again, using the same parameters, it worked just fine.

**Comment by macmanes** [comment] 2015-04-13 12:15
Do you have 2 different versions of Transrate installed on your system? Also, does it throw an error, or just hang 'forever'.

**Comment by nestorwendt** [comment] 2015-04-13 15:46
I'm using transrate 1.0.0.beta3 from Bintray on Ubuntu Server 14.04.2. I had transrate installed on RVM, but I removed it before getting this error. The only change in my installation is the salmon binary. I'm using the ubuntu 14.04 version, since I was encountering problems with the default salmon binary aswell.

Here's the command: 
`transrate -a assembly.fa -l all-1.fastq -i all-2.fastq -t 9`

It throws the same error you experienced.

**Comment by Blahah** [comment] 2015-06-08 12:09
This might be cleared up by moving to Salmon `v0.4.0` in transrate `v1.0.0.beta4`. If either of you experience it again with this new version please let me know.

**Closed** 2016-02-19 18:30 UTC
Labels: bug, can't reproduce
